<script>
import { generateUrl } from '@nextcloud/router';
import SettingsSection from './SettingsSection';
import SettingsGroup from './SettingsGroup';
import SettingsTextInput from './SettingsTextInput';
import CheckboxRadioSwitch from '@nextcloud/vue/dist/Components/CheckboxRadioSwitch';

export default {
  name: 'AppAdmin',
  components: {
    SettingsSection,
    SettingsGroup,
    SettingsTextInput,
    CheckboxRadioSwitch,
  },
  data() {
    return {
      clientId: '',
      secret: '',
      clientIdPlaceholder: this.$parent.clientId,
      secretPlaceholder: this.$parent.secret,
      allowSimpleSignatures: this.$parent.enableOtp,
      fileHandling: this.$parent.enableLocalSigning ? 'local' : 'remote',
      padesUrl: this.$parent.padesUrl,
    };
  },
  computed: {
    fetchSignedFileUrl() {
      return window.location.origin + this.generateNextcloudUrl('/apps/electronicsignatures/fetch_signed_file');
    },
  },
  methods: {
    generateNextcloudUrl(url) {
      return generateUrl(url);
    },
    onFileHandlingToggle(saveSetting) {
      const enableLocalSigning = this.fileHandling === 'local';
      saveSetting({ enable_local_signing: enableLocalSigning });
    },
  },
};
</script>

<template>
  <div>
    <SettingsSection :title="$t($globalConfig.appId, 'eID Easy credentials')">
      <template #settingsHint>
        <p>
          {{ $t($globalConfig.appId, 'You can find your credentials under the "My Webpages" section on your dashboard at: ') }}
          <a
              class="link"
              target="_blank"
              href="https://id.eideasy.com/">
            id.eideasy.com
          </a>
        </p>
        <p>
          {{ $t($globalConfig.appId, 'Ensure that in your eID Easy panel under "My Websites", you have added the following notification hook to your website: ') }} <b>{{ fetchSignedFileUrl }}</b>
        </p>
      </template>
      <SettingsGroup>
        <template v-slot:default="slotProps">
          <div>
            <SettingsTextInput
                v-model="clientId"
                :placeholder="clientIdPlaceholder"
                :on-button-click="() => slotProps.saveSetting({client_id: clientId})">
              <template #label>
                {{ $t($globalConfig.appId, 'Client ID') }}
              </template>
            </SettingsTextInput>
          </div>
          <div>
            <SettingsTextInput
                v-model="secret"
                :placeholder="secretPlaceholder"
                :on-button-click="() => slotProps.saveSetting({secret})">
              <template #label>
                {{ $t($globalConfig.appId, 'Secret') }}
              </template>
            </SettingsTextInput>
          </div>
        </template>
      </SettingsGroup>
    </SettingsSection>

    <SettingsSection :title="$t($globalConfig.appId, 'Features')">
      <SettingsGroup>
        <template v-slot:default="slotProps">
          <div class="checkboxWrap">
            <input
                id="allowOnlyEmail"
                v-model="allowSimpleSignatures"
                type="checkbox"
                class="checkbox"
                true-value="1"
                false-value="0"
                @change="slotProps.saveSetting({enable_otp: allowSimpleSignatures === '1'})">
            <label for="allowOnlyEmail">
              {{ $t($globalConfig.appId, 'Allow simple signatures.') }}
            </label>
          </div>
          <p>
            {{ $t($globalConfig.appId, 'Simple signatures are generated by sending a unique signing link to the signer\'s e-mail address or phone number. When the user clicks the link and expresses their consent, they are considered to have signed the document. A cryptographic e-seal will be added to the document to ensure that the document is not modified after it was accepted by the signer. Simple signatures are easier to use, but provide lower legal certainty compared to Qualified Electronic Signatures.') }}
          </p>
          <p>
            {{ $t($globalConfig.appId, 'Please note that Simple Electronic Signatures are always collected remotely, in order to increase the legal value of the signature.') }}
          </p>
        </template>
      </SettingsGroup>
    </SettingsSection>

    <SettingsSection :title="$t($globalConfig.appId, 'File handling')">
      <template #settingsHint>
        <p>
          {{ $t($globalConfig.appId, 'This setting determines how and where the files are signed.') }}
        </p>
      </template>
      <SettingsGroup>
        <template v-slot:default="slotProps">
          <CheckboxRadioSwitch
              :checked.sync="fileHandling"
              value="remote"
              name="signing_mode_radio"
              type="radio"
              @update:checked="onFileHandlingToggle(slotProps.saveSetting)">
            {{ $t($globalConfig.appId, 'Remote with eID Easy') }}
          </CheckboxRadioSwitch>
          <p>
            {{ $t($globalConfig.appId, 'With remote signing, the files are sent to the eID Easy server. The signer will go to a signing page on the eID Easy site, where they will be guided through the signing process.') }}
          </p>
          <CheckboxRadioSwitch
            :checked.sync="fileHandling"
            value="local"
            name="signing_mode_radio"
            type="radio"
            @update:checked="onFileHandlingToggle(slotProps.saveSetting)">
            {{ $t($globalConfig.appId, 'Local') }}
          </CheckboxRadioSwitch>
          <p>
            {{ $t($globalConfig.appId, 'With local signing, the signer is directed to your Nextcloud instance for the signing process. They will not need an account in your Nextcloud instance. The files never leave your server. The file names and signatory names will pass through eID Easy server, to enable electronic signature creation.') }}
          </p>
          <p>
            {{ $t($globalConfig.appId, 'Note: local signing currently supports only smart-card (e.g. personal id-card) based signatures.') }}
          </p>
          <p>
            {{ $t($globalConfig.appId, 'To enable local signing for pdf containers, you must set up a PADES service on your server. To do this:') }}
          </p>
          <ol>
            <li>{{ $t($globalConfig.appId, 'Install docker') }}</li>
            <li>{{ $t($globalConfig.appId, 'Pull the service container into the directory of your choice: docker pull eideasy/pades-external-digital-signatures') }}</li>
            <li>cd eideasy-external-pades-digital-signatures/</li>
            <li>{{ $t($globalConfig.appId, 'Start the container: ') }}<span v-pre>sudo docker run -p 8080:8084 --name=eideasy_detached_pades --restart always --log-driver syslog --log-opt tag="{{.Name}}/{{.ID}}" eideasy/pades-external-digital-signatures</span></li>
            <li>{{ $t($globalConfig.appId, 'Provide the container\'s url for the PADES URL setting below. If you didn\'t change the above "docker run" command, the url is 0.0.0.0:8080.') }}</li>
          </ol>
        </template>
      </SettingsGroup>
      <SettingsGroup>
        <template v-slot:default="slotProps">
          <SettingsTextInput
              v-model="padesUrl"
              :placeholder="padesUrl"
              :on-button-click="() => slotProps.saveSetting({pades_url: padesUrl})">
            <template #label>
              {{ $t($globalConfig.appId, 'PADES URL') }}
            </template>
          </SettingsTextInput>
        </template>
      </SettingsGroup>
    </SettingsSection>
  </div>
</template>

<style scoped>
  .link {
    color: #0082c9;
  }

  p {
    margin-bottom: 10px;
  }

  ol {
    list-style: none;
    counter-reset: list-item-counter;
  }

  ol li {
    counter-increment: list-item-counter;
  }

  ol li::before {
    content: counter(list-item-counter) '. ';
  }
</style>
